# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_category',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Category'),
        ),
    ]
